[build]
publish = "public"
command = "npm install && export PATH=$PATH:./node_modules/.bin && hugo --gc --minify --ignoreCache"

[build.environment]
HUGO_VERSION = "0.147.2"
NODE_VERSION = "20"
NPM_FLAGS = "--legacy-peer-deps"
SASS_PATH = "./node_modules/.bin/sass"

[build.processing]
skip_processing = false

[build.processing.images]
compress = true

[functions]
node_bundler = "esbuild"

[context.production.environment]
HUGO_VERSION = "0.147.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "20"
NPM_FLAGS = "--legacy-peer-deps"

[context.split1]
command = "npm install && export PATH=$PATH:./node_modules/.bin && hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.147.2"
HUGO_ENV = "production"
NODE_VERSION = "20"
NPM_FLAGS = "--legacy-peer-deps"

[context.deploy-preview]
command = "npm install && export PATH=$PATH:./node_modules/.bin && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.147.2"
NODE_VERSION = "20"
NPM_FLAGS = "--legacy-peer-deps"

[context.branch-deploy]
command = "npm install && export PATH=$PATH:./node_modules/.bin && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.147.2"
NODE_VERSION = "20"
NPM_FLAGS = "--legacy-peer-deps"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''